### ISSUE TITLE
Kicking a vehicle Kills the car.

### ISSUE THREAD

**Issue by SkrippyBoi** [QuantumMalice/vehiclehandler#1]
A minor bug ive found is that kicking a car usually KOs a car within 1/2 kicks 

Replication: Have Player 1 in the car, and Player 2 Kicks the car. Boom car dead. 

Something i tried was to set the weapon damage on the vehicle to a lower level, which worked for normal guns, but not kicking.

Used this native SetVehicleHandlingFloat(vehEntity, 'CHandlingData', 'fWeaponDamageMult', 2 / 3)

**Comment by QuantumMalice** [comment]
The issue you are describing pertains to **weapon damage**, this script does not handle damage outputs but rather the damage that a vehicle *receives*. It sounds like you need to lower your unarmed modifier.

## Try this instead:
```lua
CreateThread(function()
    SetWeaponDamageModifier(`WEAPON_UNARMED`, 0.1)
end)
```
