### ISSUE TITLE
Error on player join

### ISSUE THREAD

**Issue by sfxcustoms** [QuantumMalice/vehiclehandler#3]
SCRIPT ERROR: @vehiclehandler/modules/handler.lua:87: attempt to index a nil value (field 'private')
setSeat (@vehiclehandler/modules/handler.lua:87)
?  (@vehiclehandler/client.lua:151)
fn (@ox_lib/init.lua:185)
set (@ox_lib/resource/cache/client.lua:7)
fn (@ox_lib/resource/cache/client.lua:41)

**Comment by QuantumMalice** [comment]
Have you updated to _v1.2.3_, the latest version? I pushed a hotfix earlier today to resolve this. Let me know if the issue still persists.

**Comment by sfxcustoms** [comment]
> Have you updated to _v1.2.3_, the latest version? I pushed a hotfix earlier today to resolve this. Let me know if the issue still persists.

Hi, the issue still persist

I have using ESX Multicharacter does this maybe the issue? with multicharacter sometime with other script we need to check if the player is loaded using ESX.PlayerLoaded before initializing some functions

**Comment by QuantumMalice** [comment]
This seems to only be affecting ESX users, as I cannot recreate the issue in ox or qbox. It appears the seat variable within the handler class is not being initialized. I went ahead and removed the seat variable along with its methods. I reuploaded the latest release, download it again and see if it resolves the problem for you. Also, thank you for reporting this issue!

**Comment by sfxcustoms** [comment]
> This seems to only be effecting ESX users, as I cannot recreate the issue in ox or qbox. It appears the seat variable within the handler class is not being initialized. I went ahead and removed the seat variable along with its methods. I reuploaded the latest release, download it again and see if it resolves the problem for you. Also, thank you for reporting this issue!

Hi, the issue resolved for me
