### ISSUE TITLE
Error on ox inventory

### ISSUE THREAD

**Issue by mindaugasmundas** [QuantumMalice/vehiclehandler#4]
Got error when started using an item:

```
[ script:ox_inventory] SCRIPT ERROR: @ox_inventory/modules/items/shared.lua:3: No such export repairkit in resource vehiclehandler
[ script:ox_inventory] 
```

**Comment by QuantumMalice** [comment]
If you rename the script or its items, your exports **must** match. 

Refer to the overextended documentation if you're unfamiliar with how item exports work. 
[creatingItems](https://overextended.dev/ox_inventory/Guides/creatingItems)

**Comment by mindaugasmundas** [comment]
Didn't rename or anything changed. Updated completely ox_inventory and ox_lib to latest version and started to work.
